### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by forart** [webprofusion/OpenAudio#143]
Hi there, 
as you certainly know, expliciting licensing terms is extremely important for open (documentation/listings too) projects.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge:

![](https://badgen.net/github/license/webprofusion/OpenAudio)
(badge-generator URL: https://badgen.net/github/license/webprofusion/OpenAudio)

You can easily set a [compliant one](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#searching-github-by-license-type) through the GH's license wizard tool.

Thanks in advance !

**Comment by webprofusion-chrisc** [comment]
Good point! CC-0 license applied now.
