### ISSUE TITLE
Change the repo description to be Audio Software, rather than Plugins?

### ISSUE THREAD

**Issue by johnoestmannmusic** [webprofusion/OpenAudio#151]
Heyo,

Just wondering if the repo description should be updated to say "Audio Software" or "Audio Tools" rather than "VSTs and Audio Plugins", as the list now contains far more than just plugins.

Only really an issue because when you link this repo on socials/Discord/etc, people only really see that description.

Cheers,

John

**Comment by webprofusion-chrisc** [comment]
Yep, we can do that. Will comment on your PR.

**Comment by johnoestmannmusic** [comment]
Thanks!
