### ISSUE TITLE
New VST and apps

### ISSUE THREAD

**Issue by den32ds** [webprofusion/OpenAudio#23]
Audio apps - LMMS (https://lmms.io/)
Tunefish VST (https://www.tunefish-synth.com/)

**Comment by den32ds** [comment]
Juno 6 VST (https://sourceforge.net/projects/juno6/)

Audio apps - Hydrogen (http://hydrogen-music.org/)

**Comment by webprofusion-chrisc** [comment]
Hi, please feel free to try editing the README.md file on github, github should offer to create a fork which you can then submit as a Pull Request. If it's all good we can then just merge your changes.

If an app/plugin has source code online we like to link to that as well. Often domains for websites disappear but the code is still online.

**Comment by den32ds** [comment]
As you say

**Comment by webprofusion-chrisc** [comment]
Merged with #24
