### ISSUE TITLE
OpenAirLib.net is permanently down

### ISSUE THREAD

**Issue by Marat-Tanalin** [webprofusion/OpenAudio#25]
Looks like the site is [down](https://downforeveryoneorjustme.com/openairlib.net) for a while. Should it be removed?

**Comment by webprofusion-chrisc** [comment]
I'll see if I can find out more on twitter etc, this would be an awful thing to lose and should really have been hosted on github or similar to avoid a complete loss of the resource.

**Comment by webprofusion-chrisc** [comment]
For info: there is a partial export of the OpenAirLib content here but I don't know how much it represents: https://github.com/burnson/Reverb.js/tree/master/Library

**Comment by webprofusion-chrisc** [comment]
Have been informed this is a server administration issue and they are working on it.

**Comment by Marat-Tanalin** [comment]
Looks like the site is now working.
