### ISSUE TITLE
Indicate if plugin is JUCE-based

### ISSUE THREAD

**Issue by Marat-Tanalin** [webprofusion/OpenAudio#7]
Nice initiative. Would be even more useful to provide info whether specific plugins are based on the JUCE framework, this would help those interested in code samples written in pure C++/WinAPI/VSTSDK.

For example, Synister, Helm, OwlBass seem JUCE-based. Thanks.

**Comment by webprofusion-chrisc** [comment]
Obviously long term others may be based on other frameworks (or no framework), which is why I wouldn't have a 'Uses JUCE' column but we could have a badge or icon where applicable.

Pull requests appreciated as I would never get around to doing that myself.

**Comment by webprofusion-chrisc** [comment]
Unfortunately this PR directly conflicts with another one, so the discussion on how best to maintain the lists as they get long is here #16

**Comment by webprofusion-chrisc** [comment]
Resolved
