### ISSUE TITLE
plugin: neural-amp-modeler lv2

### ISSUE THREAD

**Issue by 38github** [webprofusion/OpenAudio#82]
https://github.com/mikeoliphant/neural-amp-modeler-lv2
LV2
No GUI
Simple implementation of Neural Amp Modeler (NAM). Host needs to support atom:Path which at least Ardour and Qtractor do. Reaper does not.

**Comment by webprofusion-chrisc** [comment]
Thanks, please Fork the repository, edit the readme file then submit your change as a Pull Request.

**Comment by webprofusion-chrisc** [comment]
Pretty sure if you just edit the readme file github will create a fork for you then you just need to follow the prompts to create a pull request.
